# This file is most of a Fedora CoreOS like system; it inherits from "core".
# Add things in this file which are somewhat "opinionated", not necessarily
# core functionality.

include:
  - ignition-and-ostree.yaml
  - file-transfer.yaml

initramfs-args:
  - --no-hostonly
  # We don't support root on NFS, so we don't need it in the initramfs. It also
  # conflicts with /var mount support in ignition because NFS tries to mount stuff
  # in /var/ and then ignition can't cleanly unmount it. For example:
  # https://github.com/dracutdevs/dracut/blob/1856ae95c873a6fe855b3dccd0144f1a96b9e71c/modules.d/95nfs/nfs-start-rpc.sh#L7
  # See also discussion in https://github.com/coreos/fedora-coreos-config/pull/60
  - --omit=nfs
  # Omit these since we don't use them
  - --omit=lvm
  - --omit=multipath
  - --omit=iscsi

# Be minimal
recommends: false

ignore-removed-users:
  - root
ignore-removed-groups:
  - root
etc-group-members:
  - wheel
  - sudo
  - systemd-journal
  - adm

check-passwd:
  type: "file"
  filename: "passwd"
check-groups:
  type: "file"
  filename: "group"

default-target: multi-user.target

remove-from-packages:
  # We're not using resolved yet.
  - [systemd, /usr/lib/systemd/systemd-resolved,
              /usr/lib/systemd/system/systemd-resolved.service]
  # We're not using networkd.
  - [systemd, /etc/systemd/networkd.conf,
              /usr/lib/systemd/systemd-networkd,
              /usr/lib/systemd/systemd-networkd-wait-online,
              /usr/lib/systemd/network/.*,
              /usr/lib/systemd/system/systemd-networkd.service,
              /usr/lib/systemd/system/systemd-networkd.socket,
              /usr/lib/systemd/system/systemd-networkd-wait-online.service]
  - [systemd-container, /usr/lib/systemd/network/.*]
  - [systemd-udev, /usr/lib/systemd/network/.*]


remove-files:
  # We don't ship man(1) or info(1)
  - usr/share/info
  - usr/share/man
  # Drop text docs too
  - usr/share/doc

packages:
  - atomic
  - glibc nss-altfiles shadow-utils
  - runc
  - systemd kernel rpm-ostree
  - dracut-network
  - biosdevname
  - coreutils
  - cryptsetup
  - lvm2
  - grub2 grub2-efi ostree-grub2
  - efibootmgr shim
  - e2fsprogs xfsprogs
  - mdadm
  - docker
  - docker-latest
  - docker-lvm-plugin
  - docker-novolume-plugin
  - selinux-policy-targeted
  - sssd
  - cloud-init
  - cloud-utils-growpart
  - tar xz gzip bzip2
  - less
  - kexec-tools
  - iscsi-initiator-utils
  - bridge-utils
  - nfs-utils
  - subscription-manager
  - subscription-manager-plugin-ostree
  - subscription-manager-plugin-container
  - openssh-server openssh-clients
  - chrony
  - logrotate
  - passwd
  - iptables-services
  - NetworkManager vim-minimal nano
  - sudo
  - tuned tuned-profiles-atomic
  - bubblewrap
  - fuse
  - irqbalance
  - bash-completion
  - rsync tmux
  - net-tools nmap-ncat
  - bind-utils
  - authconfig
  - policycoreutils-python
  - cockpit-shell
  - cockpit-bridge
  - cockpit-docker
  - cockpit-ostree
  - setools-console
  - device-mapper-multipath
  - sg3_utils
  - attr
  - firewalld
  - podman

# This thing is crying out to be pulled into systemd, but that hasn't happened
# yet.  Also we may want to add to rpm-ostree something like arch negation;
# basically right now it doesn't exist on s390x.
# Anyways, it was requested by the Red Hat perf team for RHCOS, so we have it here.
# https://serverfault.com/questions/513807/is-there-still-a-use-for-irqbalance-on-modern-hardware
# https://access.redhat.com/solutions/41535
packages-x86_64:
  - irqbalance
packages-ppc64le:
  - irqbalance
packages-aarch64:
  - irqbalance
